name: shoppe
description: "Shoppe is online shopping experience app include google auth and response UI with new flutter features."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  #utils
  flutter_svg: ^2.2.0

  #network
  connectivity_plus: ^6.1.4

  #state management
  get: ^4.7.2

  #Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/home/
